### ISSUE TITLE
Vare stealer 

### ISSUE THREAD

**Issue by Phantomisbest** [TaxMachine/Grabbers-Deobfuscator#10]
https://github.com/saintdaddy/Vare-Stealer

**Comment by TaxMachine** [comment]
I didn't implement any node.js deobfuscator but I'll take a look at it when I'll be free

**Comment by Phantomisbest** [comment]
ah i thought it was python cuz when i tried to decompile it, it outputted a pyc file and some long string was encrypted this is like 4 of the things from it: 
'15|05|45|201' a bunch of different numbers in a string seperated by | so idk if u know whats going on you'd find alot more than me tho i can tell u that

**Comment by TaxMachine** [comment]
This string obfuscation is typical for javascript but idk why you got pyc files. Maybe you're mixing things up

**Comment by TaxMachine** [comment]
That's weird. Its probably not the same grabber

**Comment by TaxMachine** [comment]
Btw can you send me on discord the grabber?

**Comment by Phantomisbest** [comment]
yeah sure sorry for the late reply havent been on my pc for a while im joining your discord right now

**Comment by Phantomisbest** [comment]
ah your discord invite doesnt work can u drop a quick add to my tag envyyy.me

**Comment by Phantomisbest** [comment]
ah found ur tag added u

**Comment by TaxMachine** [comment]
Deobfuscation added 👍
