### ISSUE TITLE
RoseStealer Method

### ISSUE THREAD

**Issue by FurryBoyYT** [TaxMachine/Grabbers-Deobfuscator#13]
So there's this stealer called RoseStealer and apparently when i try some methods, it does not work, so i'm recommending adding the method for it.
There is a website usually used to deobfuscator python stealers that supports RoseStealer aswell and it did get the webhook but unfortunately they do not have an open-source.

**Comment by TaxMachine** [comment]
I'll look into it

**Comment by FurryBoyYT** [comment]
> I'll look into it

found another stealer, its called Volt Stealer

**Comment by EvilBytecode** [comment]
Hi, i just wanted to say  that this is amazing repository.

**Comment by TaxMachine** [comment]
Thank you

**Comment by EvilBytecode** [comment]
Hi @TaxMachine, do you have discord? if you do. add me : ```codepulze1```

**Comment by TaxMachine** [comment]
Sent you a request

**Comment by FurryBoyYT** [comment]
> I'll look into it

Found another stealer, it's called Umbral-Stealer not sure how it works tho

**Comment by TaxMachine** [comment]
Can you add me on discord and send me all the samples?

**Comment by FurryBoyYT** [comment]
> Can you add me on discord and send me all the samples?

Sure, i sent.

**Comment by TaxMachine** [comment]
Didn't received anything

**Comment by FurryBoyYT** [comment]
> Didn't received anything

My discord is furryboy.1

**Comment by TaxMachine** [comment]
I can't add people on mobile, my discord client is retarded, add me MaxTachine

**Comment by FurryBoyYT** [comment]
> I can't add people on mobile, my discord client is retarded, add me MaxTachine

Added
