### ISSUE TITLE
have you tried this 

### ISSUE THREAD

**Issue by Germanized** [TaxMachine/Grabbers-Deobfuscator#16]
have you tried doing the stealers that inject code into discord js so it runs every time discord is opened also I really appreciate you doing this like fr u a hero

**Comment by TaxMachine** [comment]
How would this be useful? If the webhook is in the executable file already

**Comment by Germanized** [comment]
no like make deobfuscater for those types of grabbers

**Comment by Germanized** [comment]
i already made a py that checks that js after any exe i ran if its changes so im good

**Comment by TaxMachine** [comment]
No i won't make a deobfuscator for javascript, there's already alot of them out there and i still struggle even with manual deobfuscation.

**Comment by helloworld0000red** [comment]
> No i won't make a deobfuscator for javascript, there's already alot of them out there and i still struggle even with manual deobfuscation.

add empyrean pls

**Comment by TaxMachine** [comment]
Its already there
