### ISSUE TITLE
Clarification on License for this Repository

### ISSUE THREAD

**Issue by remiliacn** [TaxMachine/Grabbers-Deobfuscator#20]
Hello,

I hope this message finds you well. I have been exploring your repository, and found it very useful for malware reverse engineering. However, I couldn't find any information about the license under which this code is distributed.

Could you please clarify the license for this project? This information would help me and others determine how we can use or contribute to the project.

Thank you for your time and for sharing your work with the community!

Best.

**Comment by TaxMachine** [comment]
Its under the WTFPL, i forgot to push it

**Comment by remiliacn** [comment]
Thanks for clarification.

Updated project license information on headers! https://github.com/remiliacn/deobfuscators/commit/0418124f637d0152967f0e9d7b611345b660fd68
