### ISSUE TITLE
Fix Mehod for Creal and Empyrean please^^

### ISSUE THREAD

**Issue by Nowze** [TaxMachine/Grabbers-Deobfuscator#5]
Fix Mehod for Creal and Empyrean please^^ and add more Methods for js stealer like using jsconfuser obfuscator

**Comment by Nowze** [comment]
hello the script have not error but that say nowebhook found and say no obfuscation and no stealer detect but that empyrean and creal

**Comment by Nowze** [comment]
if u want we can go discord and voice chat^^

**Comment by TaxMachine** [comment]
@Nowze empyrean new obfuscation is not yet supported

**Comment by waxnet** [comment]
I made a pull request with a method for empyrean if you want

**Comment by TaxMachine** [comment]
Do you still need support?

**Comment by TaxMachine** [comment]
I merged a pull request that should fix it for Empyrean. I don't know what doesn't work about Creal so reopen if you still need support
