### ISSUE TITLE
update it pls

### ISSUE THREAD

**Issue by luccas46** [TaxMachine/Grabbers-Deobfuscator#9]
update it pls

**Comment by TaxMachine** [comment]
Blank still works, what do you want me to update?

**Comment by luccas46** [comment]
Yeah, blank grabber is working. But, how do it work cookie such as instagram/roblox cookie?
And, do u have any backdoor monitor?
Thanks bro!

**Comment by TaxMachine** [comment]
Its just a static analysis tool. Its only to deobfuscate discord webhooks and telegram bot tokens
